In [37]:
import nltk
import string
import re
import pandas as pd
import glob
import os
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import numpy as np
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
import pickle
import math
import statistics
from statistics import mode
stop_words = set(stopwords.words('english'))

In [3]:
file_names = []
data = []
for filename in os.listdir("data_folder"):
    file_names.append(filename)
    
    try:
            f = open("data_folder/"+filename , encoding='utf8')
            var=f.read().replace('\n'," ")
            data.append(var)
            
    except Exception as e:
            f = open("data_folder/"+filename , encoding='unicode_escape')
            var=f.read().replace('\n'," ")
            data.append(var)
            
    f.close();
            

In [4]:
def preprocessing(d):
    no_punc = []
    d_lower=d.lower()
    
    nltk_tokens = nltk.word_tokenize(d_lower)
    
    stop_words_removed = []
    for w in nltk_tokens:
        if w not in stop_words:
            stop_words_removed.append(w)
    
    
    new_words = []
    for x in stop_words_removed:
        if(x.isalnum() and x!=" "):
            new_words.append(x)
        
        
    return new_words

In [5]:
word_count=0
preprocessed_data = []
for d in data:
    data_new = preprocessing(d)
    word_count = word_count  +len(data_new)
    preprocessed_data.append(data_new)    

In [6]:
print(word_count)

1071853


In [7]:
vocab_list = []
count = 0
for p in preprocessed_data :
    i=0
    for i in range(len(p)):
        if not p[i] in vocab_list:
            count=count+1
            vocab_list.append(p[i])
print(count)

67128


In [7]:
with open('Vocabulary_list' , 'wb') as f:
           pickle.dump(vocab_list , f)
with open('Vocabulary_list' , 'rb') as f:
     v_list = pickle.load(f)

In [8]:
doc_freq_list = []
for v in vocab_list:
    counter = 0
    for p in preprocessed_data:
        if v in p:
            counter=counter+1
    
    doc_freq_list.append(counter)  

In [9]:
# len(doc_freq_list)

In [10]:

with open('Document_Frequency_List' , 'wb') as f:
    pickle.dump(doc_freq_list , f)
    
with open('Document_Frequency_List' , 'rb') as f:
     new_doc_freq_list = pickle.load(f)

In [11]:
dimensions = (len(file_names) ,len(new_doc_freq_list) )
tf_idf_matrix = np.zeros(dimensions)

In [12]:
tf_idf_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
len(new_doc_freq_list)

67128

In [14]:
len(v_list)

67128

In [15]:
total_docs = len(file_names)
#i=0
for i in range(len(v_list)):
    idf = math.log10(total_docs/(new_doc_freq_list[i]+1))
    #j=0
    for j in range(len(file_names)):
        tf_idf_matrix[j][i] = idf    

In [16]:
tf_idf_matrix1 = tf_idf_matrix
tf_idf_matrix2 = tf_idf_matrix
tf_idf_matrix3 = tf_idf_matrix
tf_idf_matrix4 = tf_idf_matrix
tf_idf_matrix5 = tf_idf_matrix

In [17]:
#tfid matrix with term weighing scheme (Binary)
for i in range(len(v_list)):
    word = v_list[i]
    for j in range(len(file_names)):
        if word not in preprocessed_data[j]:
            tf_idf_matrix1[j][i] = 0

In [18]:
# tf_idf_matrix1

In [19]:
with open('tf_idf_mat1' , 'wb') as f:
        pickle.dump(tf_idf_matrix1 , f)
        
with open('tf_idf_mat1' , 'rb') as f:
     tf_idf_1 = pickle.load(f)

In [20]:
tf_idf_1

array([[2.75319991, 2.75319991, 1.90810187, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 2.75319991, 2.75319991,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.75319991]])

In [21]:
def method1(query_mod , tf_idf):
    tfidf_net = []
    for i in range(len(file_names)):
        s = 0
        for q in query_mod:
            j = v_list.index(q)
            s = s + tf_idf[i][j]
        tfidf_net.append(s)
    Z = [x for _,x in sorted(zip(tfidf_net,file_names))]
    Z.reverse()
    
    return Z,tfidf_net

In [133]:
query = input("Enter a query")
query_mod = preprocessing(query)
Z,tfidf_net = method1(query_mod,tf_idf_1)
for i in range(5):
    print(Z[i])

Enter a querydaily music television show with guests
mlverb.hum
manners.txt
humor9.txt
aboutada.txt
sfmovie.txt


In [134]:
query_mod

['daily', 'music', 'television', 'show', 'guests']

In [135]:
# tfid matrix with term weighing scheme (Raw count)
for i in range(len(v_list)):
    word = v_list[i]
    for j in range(len(file_names)):
        if word not in preprocessed_data[j]:
            tf_idf_matrix2[j][i] = 0
        else:
            tf_idf_matrix2[j][i] = tf_idf_matrix2[j][i] * preprocessed_data[j].count(word)
            

In [24]:
with open('tf_idf_mat2' , 'wb') as f:
        pickle.dump(tf_idf_matrix2 , f)
        
with open('tf_idf_mat2' , 'rb') as f:
     tf_idf_2 = pickle.load(f)

In [25]:
tf_idf_2

array([[2.75319991, 2.75319991, 3.81620375, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 2.75319991, 2.75319991,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        5.50639983]])

In [146]:
Z,tfidf_net = method1(query_mod,tf_idf_2)
for i in range(5):
    print(Z[i])

commword.hum
rns_ency.txt
stuf10.txt
manners.txt
sf-zine.pub


In [28]:
# tfid matrix with term weighing scheme (Term frequency)
tf_idf_3 = tf_idf_2
for i in range(len(file_names)):
    doc_length = len(preprocessed_data[i])
    for j in range(len(v_list)):
        tf_idf_3[i][j] = tf_idf_3[i][j]/doc_length   

In [30]:
query = input("Enter a query")
query_mod = preprocessing(query)
Z,tfidf_net = method1(query_mod,tf_idf_3)
for i in range(5):
    print(Z[i])

Enter a querydaily music television show with guests
popmusi.hum
aboutada.txt
commword.hum
hbo_spec.rev
rocking.hum


In [31]:
# tfid matrix with term weighing scheme (Log Normalization)
for i in range(len(v_list)):
    word = v_list[i]
    for j in range(len(file_names)):
        if word not in preprocessed_data[j]:
            tf_idf_matrix4[j][i] = 0
        else:
            tf_idf_matrix4[j][i] = tf_idf_matrix4[j][i] * math.log10(1+preprocessed_data[j].count(word))
            

In [32]:
with open('tf_idf_mat4' , 'wb') as f:
        pickle.dump(tf_idf_matrix4 , f)
        
with open('tf_idf_mat4' , 'rb') as f:
     tf_idf_4 = pickle.load(f)

In [33]:
tf_idf_4

array([[0.82879576, 0.82879576, 0.91039596, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.82879576, 0.82879576,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.3136102 ]])

In [34]:
query = input("Enter a query")
query_mod = preprocessing(query)
Z,tfidf_net = method1(query_mod,tf_idf_4)
for i in range(5):
    print(Z[i])

Enter a querydaily music television show with guests
manners.txt
humor9.txt
mlverb.hum
aboutada.txt
stuf10.txt


In [38]:
# tfid matrix with term weighing scheme (Double Normalization)
for i in range(len(v_list)):
    word = v_list[i]
    for j in range(len(file_names)):
        if word not in preprocessed_data[j]:
            tf_idf_matrix5[j][i] = tf_idf_matrix5[j][i] * 0.5
        else:
            most_freq_word = mode(preprocessed_data[j])
            most_freq_count = preprocessed_data[j].count(most_freq_word)
            tf_idf_matrix5[j][i] = tf_idf_matrix5[j][i] * (0.5 + 0.5*(preprocessed_data[j].count(word)/most_freq_count))

In [39]:
with open('tf_idf_mat5' , 'wb') as f:
        pickle.dump(tf_idf_matrix5 , f)
with open('tf_idf_mat5' , 'rb') as f:
     tf_idf_5 = pickle.load(f)

In [40]:
tf_idf_5

array([[0.48346419, 0.48346419, 0.60693064, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.49727745, 0.49727745,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.98520765]])

In [41]:
query = input("Enter a query")
query_mod = preprocessing(query)
Z,tfidf_net = method1(query_mod,tf_idf_5)
for i in range(5):
    print(Z[i])

Enter a querydaily music television show with guests
commword.hum
manners.txt
popmusi.hum
aboutada.txt
humor9.txt
